services:
  food-ordering-mysql-db:
    container_name: food-ordering-mysql-db
    image: mysql:8.0.32
    ports:
      - '${FOOD_ORDERING_MYSQL_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${FOOD_ORDERING_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${FOOD_ORDERING_MYSQL_DB_NAME}
      LANG: C.UTF-8
    volumes:
      - ./.volumes/mysql/mysql-volume:/var/lib/mysql
      - ./.volumes/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysqladmin ping -u root -p${FOOD_ORDERING_MYSQL_PASSWORD}"
    networks:
      - food-ordering-network

  food-ordering-phpmyadmin:
    container_name: food-ordering-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${FOOD_ORDERING_PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: food-ordering-mysql-db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${FOOD_ORDERING_MYSQL_PASSWORD}
    depends_on:
      - food-ordering-mysql-db
    networks:
      - food-ordering-network

  food-ordering-mailhog:
    container_name: food-ordering-mailhog
    image: mailhog/mailhog:latest
    ports:
      - '${FOOD_ORDERING_MAILHOG_SERVER_PORT}:1025'
      - '${FOOD_ORDERING_MAILHOG_UI_PORT}:8025'
    environment:
      - 'MH_STORAGE=maildir'
      - 'MH_MAILDIR_PATH=/home/mailhog'
    volumes:
      - ./.volumes/mail/mailhog-volume:/home/mailhog
      - ./.volumes/mail/mailhog.conf:/etc/supervisor/conf.d
      - ./.volumes/mail/mailhog-auth.txt.txt:/etc/mailhog-auth.txt.txt
    healthcheck:
      test: [ "CMD", "echo | telnet 127.0.0.1 8025" ]
      interval: 1m30s
      timeout: 5s
      retries: 3
    networks:
      - food-ordering-network

  food-ordering-app:
    container_name: food-ordering-app-hot-reload
    ports:
      - '${FOOD_ORDERING_PHP_SERVER_PORT}:80'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./.htaccess:/var/www/html/.htaccess
    environment:
      # server properties
      APACHE_RUN_USER: '#1000'
      APACHE_RUN_GROUP: '#1000'
      # app properties
      DB_DSN: mysql:host=food-ordering-mysql-db;dbname=${FOOD_ORDERING_MYSQL_DB_NAME}
      DB_USERNAME: root
      DB_PASSWORD: ${FOOD_ORDERING_MYSQL_PASSWORD}
      SMTP_HOST: food-ordering-mailhog
      SMTP_PORT: 1025
      SMTP_USERNAME: admin
      SMTP_PASSWORD: admin
      SMTP_SENDER: noreply@food-ordering.dev
      SMTP_LOOPBACK: info@food-ordering.dev
      SMTP_ENCRYPTION_TYPE: '' # ''/tls/ssl
    depends_on:
      - food-ordering-mysql-db
      - food-ordering-mailhog
    networks:
      - food-ordering-network

networks:
  food-ordering-network:
    driver: bridge
