name: Update Dockerhub README

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/docker-readme.yml"
      - "docker/README.md"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: milosz08/food-ordering-web-app
          readme-filepath: ./docker/README.md
          short-description: "Full stack web application written in PHP with embedded MVC framework written from scratch."
